Moved functions to a new file

diff --git a/innit b/innit
--- a/innit
+++ b/innit
@@ -1,56 +1,10 @@
 #!/bin/bash
 
-convert.fahrenheit () {
-	local input=$1
-	echo "$(awk -vinput="$input" 'BEGIN{print (input - 32) / 1.8}') C"
-}
-
-convert.mile () {
-	local input=$1
-	echo "$(awk -vinput="$input" 'BEGIN{print input * 1.609344}') km"
-}
-
-convert.yard () {
-	local input=$1
-	echo "$(awk -vinput="$input" 'BEGIN{print input / 1.0936}') m"
-	echo "Who the hell still uses yards?"
-}
-
-convert.foot () {
-	local input=$1
-	echo "$(awk -vinput="$input" 'BEGIN{print input * 0.3048}') m"
-}
-
-convert.inch () {
-	local input=$1
-	echo "$(awk -vinput="$input" 'BEGIN{print input * 2.54}') cm"
-}
-
-convert.pound () {
-	local input=$1
-	echo "$(awk -vinput="$input" 'BEGIN{print input * 0.45359237}') kg"
-}
-
-convert.gallon () {
-	local input=$1
-	echo "$(awk -vinput="$input" 'BEGIN{print input / 0.2641720524}') L"
-}
-
-convert.mileperhour() {
-	local input=$1
-	echo "$(awk -vinput="$input" 'BEGIN{print input / 0.6213711922}') kmh"
-}
-
-get.unit () {
-	local arg=$1
-	arg="${arg//[[:punct:]]/}"
-	echo "${arg//[[:digit:]]/}"
-}
-
-get.value () {
-	local arg=$1
-	echo "${arg//[[:alpha]]/}"
-}
+if [[ -f "${0%/*}/conversions" ]]; then
+	. "${0%/*}/conversions"
+else
+	echo "ERROR! Cannot find conversions file." >&2
+fi
 
 unit=$(get.unit $1)
 value=$(get.value $1)
@@ -65,6 +19,7 @@ case $unit in
 	lb)	convert.pound "$value";;
 	gal)	convert.gallon "$value";;
 	mph)	convert.mileperhour "$value";;
+	acre) convert.acre "$value";;
 	*)	echo "ERROR! Unit is not supported!" >&2;;
 esac
 shopt -u nocasematch
diff --git a/merika b/merika
--- a/merika
+++ b/merika
@@ -1,61 +1,11 @@
 #!/bin/bash
 
-convert.celsius () {
-	local input=$1
-	echo "$(awk -vinput="$input" 'BEGIN{print input * 1.8 + 32}') F"
-}
+if [[ -f "${0%/*}/conversions" ]]; then
+	. "${0%/*}/conversions"
+else
+	echo "ERROR! Cannot find conversions file." >&2
+fi
 
-convert.kelvin () {
-	local input=$1
-	echo "$(awk -vinput="$input" 'BEGIN{print input * 1.8 - 459.67}') F"
-}
-
-convert.kilometer () {
-	local input=$1
-	echo "$(awk -vinput="$input" 'BEGIN{print input / 1.609344}') mi"
-}
-
-convert.meter () {
-	local input=$1
-	echo "$(awk -vinput="$input" 'BEGIN{print input / 0.3048}') ft"
-}
-
-convert.centimeter () {
-	local input=$1
-	echo "$(awk -vinput="$input" 'BEGIN{print input / 2.54}') in"
-}
-
-convert.kilogram () {
-	local input=$1
-	echo "$(awk -vinput="$input" 'BEGIN{print input / 0.45359237}') lb"
-}
-
-convert.stone () {
-	local input=$1
-	echo "$(awk -vinput="$input" 'BEGIN{print input * 14}') lb"
-	echo "Who the hell still uses stone?"
-}
-
-convert.liter () {
-	local input=$1
-	echo "$(awk -vinput="$input" 'BEGIN{print input * 0.2641720524}') gal"
-}
-
-convert.kmperhour () {
-	local input=$1
-	echo "$(awk -vinput="$input" 'BEGIN{print input * 0.6213711922}') mph"
-}
-
-get.unit () {
-	local arg=$1
-	arg="${arg//[[:punct:]]/}"
-	echo "${arg//[[:digit:]]/}"
-}
-
-get.value () {
-	local arg=$1
-	echo "${arg//[[:alpha]]/}"
-}
 
 unit=$(get.unit $1)
 value=$(get.value $1)
